# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCitationCFF: true
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: false
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: true
AddLintCI: true
AddLychee: true
AddMacToCI: true
AddPrecommit: true
AddPrecommitUpdateCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: true
Authors: Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors
CheckExplicitImports: true
CodeOfConductContact: abel.s.siqueira@gmail.com
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
GitHubActionVersionAutoUpdate: dependabot
JuliaCompatAutoUpdate: dependabot
JuliaIndentation: 2
JuliaMinCIVersion: lts
JuliaMinVersion: '1.6'
License: MPL-2.0
LicenseCopyrightHolders: Abel Soares Siqueira
MarkdownIndentation: 2
PackageName: BestieTemplate
PackageOwner: JuliaBesties
PackageUUID: e5d671a7-4186-4f1a-bf88-c19b630da94f
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 3
StrategyReviewExcluded: true
TestingStrategy: testitem_cli
UseCirrusCI: false
_commit: v0.18.2
_src_path: .
