exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://github.com/.*/compare/v.*HEAD$",
  "^https://blog.esciencecenter.nl" # certificate error, hopefully fixed soon
]

exclude_path = [
  "docs/build",
  "test/conda-env"
]
