repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: .JuliaFormatter.toml
        args: [--unique]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        types_or: [yaml, json]
        exclude: ".copier-answers.yml"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/domluna/JuliaFormatter.jl
    rev: v1.0.35
    hooks:
      - id: julia-formatter
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
