name: "Feature Request"
description: Suggest a new feature for the package
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please, before submitting, make sure that:

        - There is not an [existing issue](https://github.com/abelsiqueira/BestieTemplate.jl/issues) with the same question
        - You have read the [contributing guide](https://github.com/abelsiqueira/BestieTemplate.jl/blob/main/docs/src/90-contributing.md/)
        - You are following the [code of conduct](https://github.com/abelsiqueira/BestieTemplate.jl/blob/main/CODE_OF_CONDUCT.md)

        The form below should help you in filling out this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the requested feature
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is relevant
  - type: textarea
    id: target
    attributes:
      label: Target audience
      description: Tell more about the users of this feature, or where it could be useful
  - type: textarea
    id: can-help
    attributes:
      label: Can you help
      description: Can you help developing this feature?
