name: "Usage question"
description: Questions related to the usage
labels: ["usage docs"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please, before submitting, make sure that:

        - You have checked the [documentation](https://abelsiqueira.github.io/BestieTemplate.jl) and haven't found enough information
        - There is not an [existing issue](https://github.com/abelsiqueira/BestieTemplate.jl/issues) with the same question
        - You have read the [contributing guide](https://github.com/abelsiqueira/BestieTemplate.jl/blob/main/docs/src/90-contributing.md/)
        - You are following the [code of conduct](https://github.com/abelsiqueira/BestieTemplate.jl/blob/main/CODE_OF_CONDUCT.md)

        The form below should help you in filling out this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write your question
    validations:
      required: true
