"""Integration tests: real copier runs against the local template checkout.

These mirror the golden expectations of the Julia suite
(test/test-add-feature.jl): same template, same features, same invariants.
`ref="HEAD"` matches the Julia tests' `use_latest = true` (the working tree,
not the latest release).
"""

from pathlib import Path

import pytest

import bestie_template

pytestmark = pytest.mark.integration


@pytest.fixture
def template(repo_root):
    return str(repo_root)


def test_agents_on_empty_folder(tmp_path, template):
    result = bestie_template.add_feature(
        ["agents"], tmp_path, data={"PackageName": "FakePkg"}, template=template, ref="HEAD"
    )
    agents_md = tmp_path / "AGENTS.md"
    assert agents_md.is_file()
    content = agents_md.read_text()
    assert "FakePkg" in content and "Pkg.test()" in content
    # add_feature never creates an answers file
    assert not (tmp_path / ".copier-answers.yml").exists()
    assert result.applied[0].files == ("AGENTS.md",)
    assert not result.answers_file_updated


def test_testitem_cli_on_empty_folder(tmp_path, template):
    # No data at all: testitem_cli has no required fields (placeholders cover the rest)
    bestie_template.add_feature(["testitem_cli"], tmp_path, template=template, ref="HEAD")
    runtests = tmp_path / "test" / "runtests.jl"
    assert runtests.is_file()
    assert "TAGS_DATA" in runtests.read_text()
    assert not (tmp_path / ".copier-answers.yml").exists()


def test_multiple_features_and_only_their_files(tmp_path, template):
    result = bestie_template.add_feature(
        ["agents", "pre_commit"],
        tmp_path,
        data={"PackageName": "FakePkg"},
        template=template,
        ref="HEAD",
    )
    assert (tmp_path / "AGENTS.md").is_file()
    assert (tmp_path / ".pre-commit-config.yaml").is_file()
    assert (tmp_path / ".JuliaFormatter.toml").is_file()
    # Nothing outside the two features' files was generated
    generated = {path.name for path in tmp_path.iterdir()}
    assert "README.md" not in generated and "Project.toml" not in generated
    assert [applied.resolved_name for applied in result.applied] == [
        "agents",
        "pre_commit_with_config",
    ]


def test_explicit_data_beats_answers_and_answers_updated(tmp_path, template):
    (tmp_path / ".copier-answers.yml").write_text("PackageName: FromAnswers\n")
    result = bestie_template.add_feature(
        ["dependabot"],
        tmp_path,
        data={"PackageName": "ExplicitPkgName"},
        template=template,
        ref="HEAD",
    )
    dependabot = tmp_path / ".github" / "dependabot.yml"
    assert dependabot.is_file()
    content = dependabot.read_text()
    assert "ExplicitPkgName" in content and "FromAnswers" not in content
    assert result.answers_file_updated
    # The answers file was regenerated by copier, not deleted
    assert "ExplicitPkgName" in (tmp_path / ".copier-answers.yml").read_text()


def test_missing_required_fields_errors(tmp_path, template):
    from copier_features.errors import MissingRequiredFieldsError

    with pytest.raises(MissingRequiredFieldsError, match="PackageName"):
        bestie_template.add_feature(["agents"], tmp_path, template=template, ref="HEAD")
    assert not (tmp_path / "AGENTS.md").exists()


def test_existing_files_are_preserved(tmp_path, template):
    """The core invariant (Julia: _test_does_not_affect_other_files): applying
    a feature to a populated project leaves every unrelated file untouched."""
    import copier

    copier.run_copy(
        template,
        str(tmp_path),
        data={
            "PackageName": "PreservePkg",
            "PackageUUID": "01234567-89ab-4def-0123-456789abcdef",
            "Authors": "Test <test@test.org>",
            "PackageOwner": "testowner",
            "License": "MIT",
            "StrategyLevel": 0,
            "StrategyConfirmIncluded": False,
            "StrategyReviewExcluded": False,
        },
        defaults=True,
        quiet=True,
        vcs_ref="HEAD",
    )
    snapshot = {
        path.relative_to(tmp_path): path.read_bytes()
        for path in tmp_path.rglob("*")
        if path.is_file() and ".git" not in path.parts
    }
    assert snapshot, "full generation produced no files?"

    bestie_template.add_feature(["agents"], tmp_path, template=template, ref="HEAD")

    allowed_changes = {Path("AGENTS.md"), Path(".copier-answers.yml")}
    for relative, old_content in snapshot.items():
        if relative in allowed_changes:
            continue
        assert (tmp_path / relative).is_file(), f"{relative} disappeared"
        assert (tmp_path / relative).read_bytes() == old_content, f"{relative} changed"
    after = {
        path.relative_to(tmp_path)
        for path in tmp_path.rglob("*")
        if path.is_file() and ".git" not in path.parts
    }
    assert after <= set(snapshot) | allowed_changes
    assert (tmp_path / "AGENTS.md").is_file()


def test_list_features_from_local_template(template):
    names = [feature.name for feature in bestie_template.list_features(template=template)]
    assert "agents" in names and "pre_commit" in names
    descriptions = {
        feature.name: feature.description
        for feature in bestie_template.list_features(template=template)
        if feature.alias_of is None
    }
    assert all(descriptions.values())
