name: pre-commit Update

on:
  push:
    branches:
      - debug
  schedule:
    - cron: "0 7 1/7 * *" # At 7:00 every 7 days
  workflow_dispatch:

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hack for setup-python cache # https://github.com/actions/setup-python/issues/807
        run: touch requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: "3.11"
      - name: Hack for setup-python cache # https://github.com/actions/setup-python/issues/807
        run: rm requirements.txt
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit's autoupdate
        id: pre_commit_autoupdate
        run: |
          # save updated versions to file and ignore exit code
          pre-commit autoupdate | grep updating >> $HOME/pre-commit.msg || true
      - name: Apply patch to template
        run: |
          # Create patch
          git diff -- .pre-commit-config.yaml > pre-commit.patch
          # For debuggin
          cat pre-commit.patch
          # Apply patch
          patch -p1 "template/{% if AddPrecommit %}.pre-commit-config.yaml{% endif %}.jinja" pre-commit.patch
      - name: DEbug
        run: cat $HOME/pre-commit.msg
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: :robot: pre-commit update\n\n$(cat $HOME/pre-commit.msg)"
          title: "[AUTO] pre-commit update"
          body-path: "$HOME/pre-commit.msg"
          branch: auto-pre-commit-update
          delete-branch: true
          labels: chore
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
